POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nombre": "Juan",
  "correo": "juan@test.com",
  "contrasena": "123456"
}

### Login

POST http://localhost:8080/login
Content-Type: application/json

{
  "correo": "juan@test.com",
  "contrasena": "123456"
}